mdbook builds
LibertyDSNP/spec pull request #162
Opened 2022-04-05 19:50 UTC by saraswatpuneet

Problem
=======
- [x] Remove remark validate links package dependency and config
- [x] Runs remark
- [x] Runs spellcheck
- [x] Runs lint
- [x] Build mdbook (should also run link-check plugin)
- [x] Build should fail if any of the above fail
Link to GitHub Issue(s): https://github.com/LibertyDSNP/spec/issues/156

Solution
========
- [ ] Update package
- [ ] Update github workflow to add the steps towards build
- [ ]  Add deployment action but comment it out for different PR

Change summary:
---------------
- [ ] Updated package
- [ ] Renamed ci.yml to mdbook_cicd.yml

Steps to Verify:
----------------
1. Github actions mdbook_cicd should pass

2022-04-05 20:20 UTC, saraswatpuneet commented on .github/workflows/mdbook_cicd.yml
> +
Complete CI for MDBook,
Deployment to github pages needs to be set i  new PR

2022-04-05 21:06 UTC, wilwade requested changes
Nice. Just a few small updates possible and bumping to node 16 for the workflow.

2022-04-05 21:06 UTC, wilwade commented on .github/workflows/mdbook_cicd.yml
> +        run: npm i -g npm
Our package.json specifies `"engines": {"node": ">=16.14.0 <17"},`. I think we can move this to Node 16. Then we can remove the npm upgrade action. (16 defaults to npm v7+)

2022-04-05 21:06 UTC, wilwade commented on .github/workflows/mdbook_cicd.yml
> +        uses: actions/checkout@v2.3.1
Might be worth upgrading to v3.0.0 that was just released

2022-04-05 21:06 UTC, wilwade commented on .github/workflows/mdbook_cicd.yml
> +      - uses: actions/cache@v2
Looks like this one also updated to v3. Might be worth it.

2022-04-05 21:06 UTC, wilwade commented on .github/workflows/mdbook_cicd.yml
> +        run: npm run lint
This runs both lint-md and spellcheck.

2022-04-05 21:33 UTC, saraswatpuneet commented on package-lock.json
> -                "remark-validate-links": "github:wilwade/remark-validate-links#7a52742ba4d94c088929f4c1ee7fe633d5a03e07"
I think they were previously removed from package.json could not find this dependency

2022-04-05 21:34 UTC, saraswatpuneet commented on .github/workflows/mdbook_cicd.yml
> +        uses: actions/upload-artifact@v3
Good point just did

2022-04-05 21:39 UTC, saraswatpuneet commented on .github/workflows/mdbook_cicd.yml
> +
picking node lts 16.14.2

2022-04-05 21:39 UTC, saraswatpuneet commented on .github/workflows/mdbook_cicd.yml
> +
npm run lint runs both md lint, spelling checking

2022-04-05 22:02 UTC, saraswatpuneet commented on .github/workflows/mdbook_cicd.yml
> +
Tag the assets and archive

2022-04-05 22:25 UTC, saraswatpuneet commented on .github/workflows/mdbook_cicd.yml
> +      #     publish_dir: ./book
Enabled in PR https://github.com/LibertyDSNP/spec/pull/164

2022-04-06 12:28 UTC, wilwade approved these changes
👍

2022-04-06 12:36 UTC, merged