[Issue-169]: Added block/unblock graph change type
LibertyDSNP/spec pull request #170
Opened 2022-04-13 18:38 UTC by dopatraman

Problem
=======
The purpose of this PR is to propose block/unblock functionality at a protocol level.

Link to GitHub Issue(s):
https://github.com/LibertyDSNP/spec/issues/169

Google Doc with Notes / Discussion:
https://docs.google.com/document/d/1ON2cJRvZYFWmTD6VzLXNnt2B4CijrdYfWap9JH6uw9E/edit

Solution
========
This proposal includes graph change types for blocking/unblocking.

Change summary:
---------------
- [ ] Updated Spec Versions
- [ ] Tidy, well formulated change
- [ ] Another great message
- [ ] Something else I/we did

Steps to Verify:
----------------
1. A setup step / beginning state
1. What to do next
1. Any other instructions
1. Expected behavior
1. Suggestions for testing

2022-04-13 22:41 UTC, saraswatpuneet submitted a review, later dismissed

2022-04-18 13:41 UTC, saraswatpuneet approved these changes

2022-04-18 15:13 UTC, wilwade requested changes
@dopatraman Could you fill out the DIP issue with a bit more detail? I'll add some extra questions and notes in the comments over there.

2022-05-17 18:04 UTC, wilwade commented
Closing for now. We are going to think more about this with respect to private graph

2022-05-17 18:04 UTC, closed without merging