Chore/sync activity content spec/1
LibertyDSNP/spec pull request #172
Opened 2022-04-14 16:01 UTC by mehtaishita

Problem
=======
Make changes to address inconsistencies between ActivityContent package and Spec

https://github.com/LibertyDSNP/activity-content/issues/1

Solution
========
Making changes to the Activity Content portion of the spec to better clarify required values and parameter names

Change summary:
---------------
- [ ] Updated Spec Versions
- [ ] Tidy, well formulated change
- [ ] Rename URL properties for Associated types
- [ ] Update respective examples to match
- [ ] Amended Associated Type: Hash example

Steps to Verify:
----------------
1. Build spec
2. Verify changes are consistent across various attachment types - Audio, Video, Image

2022-04-14 16:11 UTC, mehtaishita commented
From description of the ticket:
_For ActvityContentHash - in spec value is required. In SDK we have dynamic values for key. - go with spec

For ActivityContentLocation - spec says name is required -
SDK has name optional - so need to resolve - required_

Both of these are required in the sdk so there are no changes to make there.

In the description, we also decided to not pluralize parameter names, so I have not renamed Video Link: Hash to Hashes. Please verify that decision

2022-04-14 20:02 UTC, shannonwells submitted a review, later dismissed
Looks good, just need to remove the block/unblock stuff.  It's out of scope for the ticket anyway.

2022-04-14 20:02 UTC, shannonwells commented on pages/DSNP/Types/GraphChange.md
> +| 2 | Block | Create a Block relationship |
We haven't yet decided to add Block/Unblock to the protocol. I think we are _mostly_ against it being in the protocol but it's still not decided.

2022-04-19 15:26 UTC, wilwade requested changes
I think we might have gotten the direction flipped on this PR. I think the changes were needed in https://github.com/LibertyDSNP/activity-content not the spec.

2022-04-19 15:36 UTC, mehtaishita commented
As in change the variable names in activity-content to href?

2022-04-19 15:47 UTC, wilwade commented
> As in change the variable names in activity-content to href?

Right. The spec is correct, the code in activity content is wrong.

2022-04-20 02:44 UTC, mehtaishita commented
I have reverted the renaming parameters for Associated Attachment types

2022-04-20 16:46 UTC, wilwade commented on pages/ActivityContent/Associated/Hash.md
> +      "value": "96a9209006748794193d1811ef2dd5f447782b8b1635841165bc031bb3db64da"
0x

2022-04-26 18:21 UTC, wilwade approved these changes

2022-05-02 19:17 UTC, merged