DIP-220 Identifier retirement
LibertyDSNP/spec pull request #224
Opened 2023-01-13 23:05 UTC by wesbiggs

Problem
=======
Per #220, retiring a user identifier is an important aspect of user control.

Solution
========
Add a Retire Identifier Operation and corresponding State Change Record. A description of the rationale and implications of identifier retirement is also added to the Identity page.

Change summary:
---------------
- [ ] Added discussion to Identity page
- [ ] Updated Operations and State Change Records

Steps to Verify:
----------------
1. Generate and review site.

2023-01-17 16:58 UTC, shannonwells commented on .yaspellerrc.json
> +    "(a )?blockchain",
This looks like a bad auto-add.  It's not in the rest of the docs.

2023-01-17 16:58 UTC, shannonwells commented on pages/DSNP/Announcements.md
> +For example, if a user creates a [Reaction Announcement](Types/Reaction.md), they may remove that reaction by creating a Tombstone Announcement.
```suggestion
For example, if a user creates a [Reaction Announcement](Types/Reaction.md), they may remove that reaction by creating a Tombstone Announcement targeting that Reaction message.
```

2023-01-17 16:58 UTC, shannonwells commented on pages/DSNP/Identity.md
> +Control entails the power to announce content associated with the Identifier and the ability to delegate permission to others to announce content on the user's behalf.
```suggestion
Control entails the power to announce content associated with the Identifier and the ability to delegate permission to others to announce content on the user's behalf, as well as to mark the content as invalid.
```

2023-01-17 16:58 UTC, shannonwells commented on pages/DSNP/Identity.md
> +An implementation MUST NOT allow the user to remove a control key if doing so would result in the user no longer being able to assert control.
Is this meant to be a more generic way of saying (by implementation example) you can't delete your only key?

2023-01-17 16:58 UTC, shannonwells commented on pages/DSNP/Identity.md
> +| Control Key | 0x00 |
Since Control keys (AccountId) in the Frequency implementation are 4 bytes, I'm not sure what this is saying.

2023-01-17 16:58 UTC, shannonwells commented on pages/DSNP/Operations.md
> +For example, an implementation might use the public key of an asymmetric key pair as a control key, and provide a proof for each operation by producing a cryptographic signature of the user's DSNP Id
Control keys also must be unique to an implementation - is that specified elsewhere?  Could we say it must be an implementation-unique public key of a cryptographic key pair of at least N bits?

2023-01-17 16:58 UTC, shannonwells commented on pages/DSNP/Overview.md
> +All state changes MUST be visible to all participants in a DSNP system.
So we are explicitly saying that you cannot be a partial participant in a DSNP system and be compliant, i.e. you can't just post GraphChange messages and keep the rest "to yourself," away from the implementation?

2023-01-31 21:02 UTC, wilwade requested changes
One tiny thing and a question

2023-01-31 21:50 UTC, wesbiggs commented on pages/DSNP/Identity.md
> +Control entails the power to invoke DSNP Operations including publishing [announcements](Announcements.md) that create, update and delete (tombstone) content associated with the Identifier, [delegati
I think `retire` is OK. Will commit your suggestion.

2023-01-31 21:57 UTC, wesbiggs commented on pages/DSNP/Identity.md
> +
1. Yes, good idea.
2. I feel like that was implied but I agree it can be made more explicit, will add.

2023-01-31 22:12 UTC, wesbiggs commented on pages/DSNP/Identity.md
> +
Added these both as an additional paragraph (not showing in the diff above, but check "Files changed").

2023-02-01 13:54 UTC, wilwade approved these changes
✅

2023-02-08 22:24 UTC, shannonwells approved these changes
🚢 it

2023-02-09 15:18 UTC, merged