Change Announcements to use multihash for hashing.
LibertyDSNP/spec pull request #245
Opened 2023-04-05 03:22 UTC by wesbiggs

Problem
=======
DSNP Announcements should use the multihash format for content hashes to avoid algorithm lock-in.

Link to GitHub Issue(s): #210

Solution
========
All Announcements that have a `contentHash` have been updated, and the section on validation of Announcements is extended to include a list of supported hashing algorithms (currently Blake2b only).

Change summary:
---------------
- [ ] Updated spec pages for Announcements

Steps to Verify:
----------------
1. Generate markdown and review

2023-04-05 20:08 UTC, wesbiggs commented on pages/DSNP/Announcements.md
> +| BLAKE2b | `blake2b-256` | `0xa0e40220` | [RFC 7693](https://tools.ietf.org/html/rfc7693) | 1.2.0 |
Let's see what the IPFS default multihash algorithm is

2023-04-06 12:09 UTC, wilwade requested changes
Looks good. One addition: needs to be added to the changelog

2023-04-06 17:23 UTC, shannonwells approved these changes
nothing to add, all good from my end

2023-04-06 19:25 UTC, wesbiggs commented
I added the Activity Content changes to this same PR.

2023-04-07 17:11 UTC, wilwade approved these changes
One whitespace and something unrelated. Nothing blocking.

2023-04-07 17:11 UTC, wilwade commented on pages/ActivityContent/Associated/Hash.md
> +	"2DrjgbGgSsXRhTiBWckoVwBFC6H4qiBWWNumSsRwdUt82YnTdN"
Whitespace
```suggestion
	"QmQNHNfHnbgJJ6nK4UPx2VtTUCafAKCbqZJ6ZRYUGjoeFj",
	"2DrjgbGgSsXRhTiBWckoVwBFC6H4qiBWWNumSsRwdUt82YnTdN"
```

2023-04-07 17:11 UTC, wilwade commented on pages/DSNP/Types/Profile.md
>  | Field | Description | Serialization | Parquet Type | Bloom Filter |
I only just noticed that `Profile` doesn't have a `Data Type` column. I think this was just an oversight. I'm ok with fixing in this or a different PR.

2023-04-07 17:11 UTC, merged